export interface FinanceSegmentInfos_DATA{
    "aggregateCostDay": number,
    "aggregateCostYear": number,
    "breakTime": number,
    "buyingRent": boolean,
    "comment": string,
    "financing": number,
    "financingMonth": number,
    "grossPay": number,
    "grossSalaryDriver": number,
    "id": number,
    "maintenanceCosts": number,
    "oneOffCosts": number,
    "overallCarCosts": number,
    "overallConsumptionsCosts": number,
    "overallMaintenanceCosts": number,
    "overallPersonalCosts": number,
    "rate": number,
    "rent": number,
    "residualValue": number,
    "salesPrice": number
}
