export interface FlowPlanCalculationResult_DATA{
    "calcNumberCars": number,
    "calcNumberCarsM1": number,
    "calcNumberCarsM2": number,
    "calcNumberCarsP1": number,
    "calcNumberCarsP2": number,
    "calcUtilizationRate": number,
    "calcUtilizationRateM1": number,
    "calcUtilizationRateM2": number,
    "calcUtilizationRateP1": number,
    "calcUtilizationRateP2": number,
    "emptyCycleRate": number,
    "executed": string,
    "loadedMissionRate": number,
    "maxTruckUtilization": number,
    "possibleLoads": number,
    "possibleLoadsPerCycle": number,
    "requiredLoadsPerCycle": number,
    "sumAllCycles": number,
    "sumEmptyCycles": number,
    "sumEngineTime": number,
    "totalDistance": number,
    "totalLoads": number,
    "totalRounds": number
}
